name: 'trash_wheel_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'motherduck_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  trash_wheel_dbt_project:
    ingest:
      materialized: table
    staging:
      materialized: view
    marts:
      materialized: table

seeds:
  trash_wheel_info:
    +quote_columns: false

vars:
  source_google_sheet_link: "https://docs.google.com/spreadsheets/d/1b8Lbe-z3PNb3H8nSsSjrwK2B0ReAblL2"