name: 'trash_wheel_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'motherduck_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  trash_wheel_dbt_project:
    materialized: view
    ingest:
      # schema: raw
      materialized: table
    staging:
      # schema: stg
      materialized: table
    mart:
      # schema: mart
      materialized: table
