name: dbt_ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dbt_ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
      DBT_PROJECT_DIR: ${{ github.workspace }}/dbt_pipeline
      DBT_PROFILES_DIR: ${{ github.workspace }}/dbt_pipeline/.dbt

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Set up dbt profiles
        # "initializeCommand": "mkdir -p /root/dbt_pipeline/.dbt && cp dbt_pipeline/profiles.yml /root/dbt_pipeline/.dbt/"
        run: |
          mkdir -p ${{ env.DBT_PROJECT_DIR }}/.dbt
          cp ${{ env.DBT_PROJECT_DIR }}/profiles.yml ${{ env.DBT_PROFILES_DIR }}/profiles.yml
        shell: bash
  
      # - name: Run dbt deps
      #   run: dbt deps
      #   working-directory: ${{ env.DBT_PROJECT_DIR }}
  
      - name: Run dbt test
        run: dbt test
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Run dbt
        run: dbt run
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: dir docs dir
        run: |
          mkdir -p ${{ github.workspace }}/docs/pipeline
          mkdir -p ${{ github.workspace }}/docs/dashboard

      - name: Generate dbt doc
        run: dbt docs generate --target-path ${{ github.workspace }}/docs/pipeline
        working-directory: ${{ env.DBT_PROJECT_DIR }}
        
      # Github Page deploy
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/docs
      
      - name: Deploy docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
